#!/bin/bash
# Quick checklist for Edge Function deployment

echo "📋 Supabase Edge Function Deployment Checklist"
echo "=============================================="
echo ""
echo "Before deploying the admin-notify Edge Function, ensure:"
echo ""
echo "[ ] 1. Supabase project created"
echo "       - Sign up at https://supabase.com"
echo "       - Create a new project"
echo ""
echo "[ ] 2. Supabase CLI installed"
echo "       - npm install -g supabase"
echo "       - supabase login"
echo ""
echo "[ ] 3. Resend account created"
echo "       - Sign up at https://resend.com"
echo "       - Create API key at https://resend.com/api-keys"
echo "       - Copy and save your API key"
echo ""
echo "[ ] 4. Deploy Edge Function"
echo "       - Run: supabase functions deploy admin-notify --project-id <project-id>"
echo ""
echo "[ ] 5. Set Supabase secrets"
echo "       - Go to Supabase dashboard → Project Settings → Edge Functions"
echo "       - Set these secrets:"
echo "         • RESEND_API_KEY = (your API key from Resend)"
echo "         • ADMIN_NOTIFY_TO_EMAIL = (your email)"
echo "         • ADMIN_NOTIFY_ALLOWED_ORIGINS = https://anuragverma-author.vercel.app"
echo ""
echo "[ ] 6. Get function URL"
echo "       - Go to Supabase Project Settings → Edge Functions"
echo "       - Copy the admin-notify function URL"
echo ""
echo "[ ] 7. Set Vercel environment variable"
echo "       - Go to Vercel → Project Settings → Environment Variables"
echo "       - Add: VITE_ADMIN_NOTIFICATION_ENDPOINT=<function-url>"
echo ""
echo "[ ] 8. Redeploy production"
echo "       - npm run deploy"
echo ""
echo "[ ] 9. Test the forms"
echo "       - Submit a contact form"
echo "       - Check your email for notifications"
echo "       - Check browser DevTools Network tab for requests to the Edge Function"
echo ""
echo "✅ All done! Your app now has first-party email notifications."
